name: GitHub Actions Pipelinee
on:
  push:
    branches:
      - main

jobs:
  invoke_api:
    runs-on: windows-latest
    steps:
      - name: Install OpenVPN
        run: |
          choco install openvpn
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          where openvpn
      - name: Set up VPN connection
        run: |
              Start-Process -FilePath "C:\ProgramData\chocolatey\bin\openvpn.exe" -WorkingDirectory "C:\ProgramData\chocolatey\bin" -ArgumentList @("--config", "F:\OpenVPN\pfSense-udp-1194-config.ovpn", "--daemon")
              Start-Sleep -s 10  # Wait for the VPN connection to establish
      - name: Call REST API
        run: |
          $BatchscheduleID = '${{ secrets.BATCHSCHEDULEID }}'
          $params = @{
            Uri = 'http://172.31.19.121:8080/test-automation-via-cicd'
            Method = 'POST'
            Body = @{
              Usernameofbreez = 'qa@chartrequest.com'
              Passwordofbreez = 'tsq@123'
              BatchscheduleID = $BatchscheduleID
              IpAddress = 'http://172.31.19.121:8080/'
            }
          }
