name: GitHub Actions Pipeline
on:
  push:
    branches:
      - main
jobs:
  invoke_api:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install OpenVPN
        run: |
          choco install openvpn
      - name: Connect to VPN
        run: |
           Start-Process -FilePath "openvpn" -ArgumentList "--config", ".github/workflows/pfSense-udp-1194-config.ovpn", "--daemon", "--log", "openvpn.log", "--writepid", "openvpn.pid", "--username", "${{ secrets.OVPN_USERNAME }}", "--password", "${{ secrets.OVPN_PASSWORD }}" -Verb RunAs
      - name: Call REST API
        run: |
          $BatchscheduleID = '${{ vars.BATCHSCHEDULEID }}'
          $params = @{
            Uri = 'http://172.31.19.121:8080/test-automation-via-cicd'
            Method = 'POST'
            Body = @{
              Usernameofbreez = 'qa@chartrequest.com'
              Passwordofbreez = 'tsq@123'
              BatchscheduleID = $BatchscheduleID
              IpAddress = 'http://172.31.19.121:8080/'
            }
          }
          Invoke-RestMethod @params
