name: GitHub Action
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install OpenVPN and jq
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved jq
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: .github/workflows/pfSense-udp-1194-config.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
          client_key: ${{ secrets.USER_KEY }}
      - name: Define BatchscheduleID variable
        run: |
          echo "BATCHSCHEDULEID=your_batch_schedule_id" >> $GITHUB_ENV
      - name: Call REST API
        run: |
         response=$(curl -X POST  --location 'http://172.31.19.121:8080/test-automation-via-cicd' -d "Usernameofbreez=qa@chartrequest.com&Passwordofbreez=tsq@123&BatchscheduleID=${{ vars.BATCHSCHEDULEID }}&IpAddress=http://172.31.19.121:8080/")
         echo "API Response: $response"
